In [1]:
import pandas as pd
import sys

sys.path.insert(0, r"/home/westerd/_/research_projects/tedla-hypertension/src")

In [2]:
from data_extract.datasources.cohort_data import CohortData

cohort_data = CohortData()
df = cohort_data.get()
assert isinstance(df, pd.DataFrame)
print(df.head())
del cohort_data

   deid_pat_id       mrn  person_id
0       815539  13804349    5558677
1       517658  16111171    5817330
2       559114  34371286    6328796
3       506813  11910064    8857667
4       314006  34084558    5328339

In [3]:
from typing import Generator

from data_extract.datasources.data_to_process import DataToProcess

data_to_process = DataToProcess()
df = data_to_process.get(batch_size=10)
display(next(df).head())
del data_to_process

,note_id,person_id,x_part_num,x_uniq,note_date,visit_occurrence_id,is_patient_communication,note_within_visit
0,5838851739043601132,12021053,1.0,1258553849,2021-09-09,318093416.0,False,None
1,5962036047194007624,9912263,1.0,163771959,2020-03-12,245542556.0,False,None
2,5906161477316100639,6900390,1.0,1169560601,2021-07-09,306711047.0,False,None
3,5859002541767698329,13733486,NaN,32730366,2021-11-09,NaN,False,None
4,5890362938063667721,7579845,3.0,66818372,2018-02-12,NaN,False,None

In [ ]:
from data_extract.datasources.note_group_map import NoteGroupMap

note_group_map = NoteGroupMap()
df = note_group_map.get(batch_size=10)
display(next(df).head(20))
del note_group_map

   note_group_id                           note_group
0              1                admission_notes_group
1              2  communication_encounter_notes_group
2              3        discharge_summary_notes_group
3              4           ecg_impression_notes_group
4              5     emergency_department_notes_group
5              6                inpatient_notes_group
6              7               outpatient_notes_group
7              8             problem_list_notes_group

In [5]:
from data_extract.datasources.notes_to_process import NotesToProcess

notes_to_process = NotesToProcess()
df = notes_to_process.get(batch_size=10)
display(next(df).head())
del notes_to_process

               note_id  note_group_id
0   591238180697721205              2
1  1648864489734375411              2
2  1242960489825118281              2
3  1993364599658747053              2
4  1019760582716127483              2

In [6]:
from data_extract.datasources.note_data import NoteData

note_data = NoteData(filter_to_datasets=["note_data_2010_to_2011_parquet"])
df = note_data.get(batch_size=10)
display(next(df).head())

total_rows: int = note_data.get_total_rows()
display(f"Total rows in dataset: {total_rows}")

del note_data

     note_id                                          note_text
0  121091696  Azithromycin 250 mg Tab Take two tablets on da...
1  130490699                  Magnesium Citrate 180 mg po daily
2  136290720                                Oxycodone as needed
3  140889160   lovenox will start per cardiologist instructions
4  147980645        Vitamin C 1000 mg one tablet by mouth daily

'Total rows in dataset: 19651503'